copy build1234abcd\combined\cps2_gfx\ffight_gfx_cps2_base_shuffled.bin build1234abcd\combined_patched\ffight_gfx_cps2.bin
copy build1234abcd\combined\ffight.bin build1234abcd\combined_patched\ffight.bin
copy build1234abcd\combined\sfa3_audio.bin build1234abcd\combined_patched\ffight_audio.bin